"""empty message

Revision ID: 17d86d6e9d8b
Revises: 26bf150370a1
Create Date: 2022-05-22 11:26:58.361414

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "17d86d6e9d8b"
down_revision = "26bf150370a1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "todos",
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column("remind_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_todos_created_at"), "todos", ["created_at"], unique=False)
    op.create_index(op.f("ix_todos_updated_at"), "todos", ["updated_at"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_todos_updated_at"), table_name="todos")
    op.drop_index(op.f("ix_todos_created_at"), table_name="todos")
    op.drop_table("todos")
    # ### end Alembic commands ###
